# Generated by Django 3.2 on 2021-06-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0002_auto_20210621_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='category',
            field=models.ForeignKey(default='babies', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='MedApp.storecategory'),
        ),
    ]
