# Generated by Django 3.2 on 2021-06-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0003_auto_20210623_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
